config/routes.rb
Rails.application.routes.draw do
  
  resources :groups do
    resources :users_groups do
      collection do 
        post "create_collection"
      end
    end
  end

  resources :projects do
    resources :project_users
  end
  resources :users

  
  root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :project_users, dependent: :destroy, foreign_key: "project_id"
  has_many :users, through: :project_users

  PROJECT_TYPES = {"外包项目" => "1", "内部项目" => "2"}

  validates_length_of :abbr_name, in: 3..255, wrong_length: "长度为%count，请输入长度为3~255的项目简称"
  validates_length_of :name, in: 5..255, wrong_length: "长度为%count，请输入长度为5~255的项目简称"
  validate :proj_end_time_cannot_be_less_than_proj_start_time
  validates :abbr_name, uniqueness: true


  def proj_end_time_cannot_be_less_than_proj_start_time
  	if proj_end_time < proj_start_time
  	  errors.add(:proj_end_time, "项目结束必须晚于项目开始时间！")
  	end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  # 编辑项目页
  def edit
  end

  # POST /projects
  # POST /projects.json
  # 创建项目
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  # 更新项目
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    # @project.destroy
    # Soft delete an item.
    @project.update_attribute(:deleted_at, Time.now)
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:abbr_name, :name, :proj_types, :proj_start_time, :proj_end_time, :deleted_at)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project, :html => { :class => "form-horizontal project" } do |f| %>

  <% if @project.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :项目简称, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :abbr_name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:abbr_name) %>
  </div>
  <div class="form-group">
    <%= f.label :项目全称, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :项目类型, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= select_tag "project[proj_types]", options_for_select({"外包项目" => "1", "内部项目" => "2"}), class: "form-control" %>
    </div>
    <%=f.error_span(:proj_types) %>
  </div>
  <div class="form-group">
    <%= f.label :项目开始时间, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <!-- <%= select_date Date.today, prefix: :start_date %> -->
      <%= date_select "project", "proj_start_time", use_two_digit_numbers: true, end_year: 2100, :class => 'form-control' %>
      <!-- <%= f.text_field :proj_start_time, :class => 'form-control' %> -->
    </div>
    <%=f.error_span(:proj_start_time) %>
  </div>
  <div class="form-group">
    <%= f.label :项目结束时间, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= date_select "project", "proj_end_time", use_two_digit_numbers: true, end_year: 2100, :class => 'form-control' %>
    </div>
    <%=f.error_span(:proj_end_time) %>
  </div>
  

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit value: "提交", :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                projects_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/projects/edit.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/index.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1>项目管理</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>项目编号</th>
      <th>项目简称</th>
      <th>项目全称</th>
      <th>项目类型</th>
      <th>项目开始时间</th>
      <th>项目结束时间</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th> 

    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <% unless project.deleted_at %>
        <tr>
          <td><%= link_to project.id, project_path(project) %></td>
          <td><%= project.abbr_name %></td>
          <td><%= project.name %></td>
          <td><%= (Project::PROJECT_TYPES).key(project.proj_types) %></td>
          <td><%= project.proj_start_time.strftime("%Y-%m-%d") %></td>
          <td><%= project.proj_end_time.strftime("%Y-%m-%d") %></td>
          <td>
            <%= link_to t('.show_users_groups', :default => t("helpers.links.show_users_groups")),
                        project_project_users_path(project), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.show', :default => t("helpers.links.show")),
                        project_path(project), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_project_path(project), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        project_path(project),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_project_path,
            :class => 'btn btn-primary' %>

app/views/projects/new.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1>新建项目</h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1>项目详情</h1>
</div>

<dl class="dl-horizontal">
<dt><strong>项目编号:</strong></dt>
  <dd><%= @project.id %></dd>
  <dt><strong>项目简称:</strong></dt>
  <dd><%= @project.abbr_name %></dd>
  <dt><strong>项目全称:</strong></dt>
  <dd><%= @project.name %></dd>
  <dt><strong>项目类型:</strong></dt>
  <dd><%= (Project::PROJECT_TYPES).key(@project.proj_types) %></dd>
  <dt><strong>项目开始时间:</strong></dt>
  <dd><%= @project.proj_start_time.strftime("%Y-%m-%d")  %></dd>
  <dt><strong>项目结束时间</strong></dt>
  <dd><%= @project.proj_end_time.strftime("%Y-%m-%d")  %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              projects_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_project_path(@project), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              project_path(@project),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>